Vagrant.configure("2") do |config|


  # config.vm.provider.memory = 512


  config.vm.define "server1" do |server1|
    server1.vm.box =  "ubuntu/bionic64"
    server1.vm.provision "shell", path: "provision.sh"
    server1.vm.hostname = "server1"
    server1.vm.network "forwarded_port", guest: 80, host: 8080
  end

  # config.vm.define "server2" do |server2|
  #    server2.vm.box =  "ubuntu/bionic64"
  #   server2.vm.hostname = "server2"
  #
  # end

end
